### ISSUE TITLE
error using tableLinks

### ISSUE THREAD

**Issue by robertrouse** [jbolda/gatsby-source-airtable-linked#5]
When I specify values for tableLinks, I get `TypeError: Cannot read property 'internal' of null`

I am specifying the tables like this:

```
tables: [
        {
          baseId: 'somebase',
          tableName: 'Books',
          tableView: 'Grid view',
          tableLinks: [`Chapters`],
        },
        {
          baseId: 'somebase',
          tableName: 'Chapters',
          tableView: 'Grid view',
        },
]
```

In this, the linked field in the "Books" table is called "Chapters" which links to records in a table of the same name. Is this the correct usage?

**Comment by robertrouse** [comment]
After some testing, I found that it fails only when using a linking field with a lot of records (hundreds or sometimes thousands). This is probably an AirTable api limit.

**Comment by robertrouse** [comment]
It is because of non-existent records in a filtered view. No issues with your code. Case closed!

**Comment by jckw** [comment]
Shouldn't it be possible to use a view that is filtered? Since we specify the view, it seems odd to disable the functionality that views are meant to apply.

**Comment by jbolda** [comment]
@jckw it is possible, but their error was due to trying to link records together that didn't exist as far as Gatsby was concerned. This was due to the fact that those records were filtered out. Hopefully that makes it more clear?
